data: '../../../dataset/LPBA/samples/'
epoch: 10
n_iters: 10000
batch_size: 32
patch_size: 31
kernel_size: 5
delta: 7
num_data: 400000
lr: 0.01
momentum: 0.99
beta: 0.999
weight_decay: 0.1
ckpt_path: '../ckpt_bn/'
